### ISSUE TITLE
The function quri.parser::parse-scheme-string is undefined when *print-case* is :downcase

### ISSUE THREAD

**Issue by vindarel** [fukamachi/quri#23]
As previously explained at https://github.com/fukamachi/dexador/issues/61, I suddenly got this error. It may be a problem of my environment, but this error shows that this function, which isn't `defun`ed but generated via a macro, can not be defined in certain cases.

I got an original error about quri which I bypassed and which I can't reproduce. I think it was related to me downgrading my Quicklisp dist. Since then I can't make a `dex:get`, and it still affects indirectly another app.

I tried deleting .fasl files I found in my project's tree, I deleted `.cache/common-lisp/sbcl-xx/*`, I upgraded to the latest Quicklisp, with no avail.

**Comment by vindarel** [comment]
I deleted `~/quicklisp/` and `~/.cache/common-lisp`: still the same. I don't know what I can do more !

**Comment by ruricolist** [comment]
Just a thought: could there be anything in your setup that is changing the default value of `*print-case*`? The way the `defun-with-array-parsing` macro is written, if `*print-case*` were `:downcase`, then the generated functions would be defined with lower-case names.

**Comment by vindarel** [comment]
Absolutely ! I have `(setf *print-case* :downcase)` in my .sbclrc. 

Deleting the cached fasl files in `~/.cache/common-lisp/` did the trick.

Thank you very, very much ! <3
