### ISSUE TITLE
Error parsing URIs

### ISSUE THREAD

**Issue by PuercoPop** [fukamachi/quri#27]
The URIs in question are

- `"http://÷ww.google.com/search?q=fuzzing"`
- `"http://éww.google.com/search?q=fuzzing"`

```lisp
(quri:uri "http://÷ww.google.com/search?q=fuzzing")

;; Invalid index 247 for (SIMPLE-ARRAY FIXNUM (128)), should be a non-negative integer below 128.
;;   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]

(quri:uri "http://éww.google.com/search?q=fuzzing")

;; Invalid index 233 for (SIMPLE-ARRAY FIXNUM (128)), should be a non-negative integer below 128.
;;   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]
```

I consider them both valid URLs given that QURI supports unicode. But even if one consider the inputs as invalid the error to be raised should be a condition that inherits from  of `quri:uri-error`.

**Comment by fukamachi** [comment]
Thank you for reporting.
I've fixed the invalid index error and make it raise a `QURI:URI-MALFORMED-STRING` instead.

I'm not sure it should support non-ASCII (and non-encoded) characters in URLs. I'm reading RFC.

**Comment by fukamachi** [comment]
It seems non-ASCII characters are not allowed in RFC, but I've made a change not to raise an error even when there's non-ASCII characters in URI authority part because it's more helpful.

Note that it still doesn't support auto encode with IDNA / Punycode the non-ASCII characters.

**Comment by aadcg** [comment]
URIs should be allowed to be built with non-ASCII characters in the domain, but they must be internally encoded via IDNA.

Otherwise, quri becomes vulnerable to IDN homograph attacks. For instance, take `google.com` and replace the `o` character by the corresponding (indistinguishable) Cyrillic character. Then both version would return as below:

```lisp
(describe (quri:uri "https://gооgle.com/"))
=>
#<QURI.URI.HTTP:URI-HTTPS https://gооgle.com/>
  [structure-object]

Slots with :INSTANCE allocation:
  SCHEME                         = "https"
  USERINFO                       = NIL
  HOST                           = "gооgle.com"
  PORT                           = 443
  PATH                           = "/"
  QUERY                          = NIL
  FRAGMENT                       = NIL
; No values
```
Until punycode is supported, I'd strongly suggest reverting 0a95ebc910ae02f3f50e613dbecd5ab1722c1cae.

**Comment by fukamachi** [comment]
Thank you for pointing out! Surely, it's not worth risking safety.
I'm reverting the commit.

**Comment by aadcg** [comment]
Thanks @fukamachi. I've added a test on 45e0ff7, so that we don't run into this issue again.
