### ISSUE TITLE
uri-path can leak into uri-host

### ISSUE THREAD

**Issue by ralt** [fukamachi/quri#29]
I think it would make sense to have some sort of error in this sort of situation?

```
CL-USER> (quri:render-uri (quri:make-uri :scheme "https" :host "foo.com" :path "foo/bar"))
"https://foo.comfoo/bar"
CL-USER> (quri:uri-host (quri:uri (quri:render-uri (quri:make-uri :scheme "https" :host "foo.com" :path "foo/bar"))))
"foo.comfoo"
```

**Comment by Ambrevar** [comment]
I have a fix here: https://github.com/Ambrevar/quri/commit/a3b7790bbe9ae488c28dd0c6db7ca525e71b1396

**Comment by Ambrevar** [comment]
Fixed in https://github.com/fukamachi/quri/commit/a3b7790bbe9ae488c28dd0c6db7ca525e71b1396.
