### ISSUE TITLE
Incorrect parsing of relative paths starting with double slash

### ISSUE THREAD

**Issue by daewok** [fukamachi/quri#31]
The first component of relative paths starting with a double slash should be the authority not the first part of the path. I.e., `(quri:parse-uri "//example.com")` Should return:
```
NIL
NIL
"example.com"
NIL
NIL
NIL
NIL
```

However, it currently returns:
```
NIL
NIL
NIL
NIL
"//example.com"
NIL
NIL
```

**Comment by Ambrevar** [comment]
@fukamachi @daewok Is this fixed with #39 then?

**Comment by daewok** [comment]
Looks like it!

**Comment by Ambrevar** [comment]
Thanks for testing!
