### ISSUE TITLE
Release 0.2?

### ISSUE THREAD

**Issue by Ambrevar** [fukamachi/quri#43]
With all the recent bug fixes, I suggest we release 0.2 to mark the change!
@fukamachi OK with that?

**Comment by fukamachi** [comment]
Sure! Sounds good to me.

**Comment by fukamachi** [comment]
Released at https://github.com/fukamachi/quri/commit/bd14ef7a676d9f11f1338d43cb98a18275a540bc.

**Comment by Ambrevar** [comment]
Oops, I forgot to mention that I wanted to merge the remaining pull requests before releasing 0.2 :p 

I'll merge them then release 0.2.1, or maybe 0.3.  What do you think?

**Comment by fukamachi** [comment]
Oh, sorry for that. 
0.2.1 will be okay if it's not so far from 0.2.

**Comment by Ambrevar** [comment]
I actually suggest to release 0.3 because the latest commits on master have a few API changes.

**Comment by Ambrevar** [comment]
Just released 0.3 with a change log because it has API-breaking changes.
I also wanted to release 0.3 before addressing the issues in #44 since they may involve many more API breaking changes.

**Comment by fukamachi** [comment]
That sounds good decision :)
Thank you for your works!
