### ISSUE TITLE
Initialize all slots to `""` instead of `NIL`

### ISSUE THREAD

**Issue by aadcg** [fukamachi/quri#61]
This would break a lot of code and ruin backwards compatibility, so it could be discussed when `1.0.0` will be released.

**Comment by Ambrevar** [comment]
Honestly, I think breaking backward  compatibility is too much a price to pay in an ecosystem that does not pin its versions.

I'd suggest releasing quri2 instead :)

**Comment by aadcg** [comment]
Fair enough.
