### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Ambrevar** [fukamachi/quri#65]
We've got the following changes on `master`:
- Constructors are exported.
- `uri=` normalizes the path so that NIL and "" are equal.
- The `file` scheme renders the query and the fragment.

OK for 0.6.0 then?

**Comment by aadcg** [comment]
Yes!

**Comment by aartaka** [comment]
Yes!

**Comment by jmercouris** [comment]
Thanks Andre!

**Comment by Ambrevar** [comment]
Done! bff2617a7d2c3f767c9407ec61ad04d277098278
