### ISSUE TITLE
merge-uri no longer accepts string parameters

### ISSUE THREAD

**Issue by rwiker** [fukamachi/quri#68]
With the rewrite of `merge-uris` in [https://github.com/fukamachi/quri/commit/8be8aa507240614abcd72daea5758501f0d856e6](https://github.com/fukamachi/quri/commit/8be8aa507240614abcd72daea5758501f0d856e6), `merge-uris` no longer accepts string parameters. This breaks some projects, and also makes `merge-uris` more difficult to use for some cases.

The fix should be simple: wrap the body of the function in

```
(let ((reference (uri reference))
        (base (uri base))
...
```

This is exactly what the previous version of the code did.

**Comment by Ambrevar** [comment]
Seems to be a fair assessment.  @aadcg Was there a specific reason you removed the `let` binding?

To avoid future confusions, we should add a comment to the fix.

**Comment by aadcg** [comment]
@rwiker thanks for reporting. 

I believe I did it because when the `path` of a `uri` can be set to NIL, the empty string or "/". That distinction becomes shady when `uri`s are instantiated from strings.

Since it breaks existing code, this should be reverted. I've opened #69.

**Comment by Ambrevar** [comment]
Merged!

**Comment by aadcg** [comment]
@Ambrevar can you close this issue? I don't have permission. Thanks.
