### ISSUE TITLE
Should `merge-uris` be more lenient towards `nil` arguments?

### ISSUE THREAD

**Issue by aadcg** [fukamachi/quri#71]
The following behaves as expected.

```lisp
(merge-uris "Potato" "https://en.wikipedia.org/wiki/") => #<URI-HTTPS https://en.wikipedia.org/wiki/Potato>
```

The question is whether the following should hold.  As of now, they raise a type error.

```lisp
(merge-uris nil "https://en.wikipedia.org/wiki/") => #<URI-HTTPS https://en.wikipedia.org/wiki/>
```

```lisp
(merge-uris "Potato" nil) => #<URI Potato>
```

```lisp
(merge-uris nil nil) => nil
```

**Comment by Ambrevar** [comment]
I don't see why not.

@aartaka Thoughts on this?

**Comment by aartaka** [comment]
There are two sides in me that fight for dominance regarding this question:
- On the one hand, interpreting `nil` as no-content is useful, and it can help with managing some mangled data.
- On the other hand, raising type error is much more reliable than silently doing stuff. One may be misled by this silence and skip the data sanitization.

If it was my personal project, I'd leave it erroring and add `hander-*` code in the places that rely on it. But I can see the benefit for e.g., Nyxt :)

**Comment by aadcg** [comment]
Absolutely agree with @aartaka.
