### ISSUE TITLE
uri parsing and rendering is inconsistent.

### ISSUE THREAD

**Issue by tmccombs** [fukamachi/quri#9]
In some situations, quri:uri and quri:render-uri are inconsitent with each other.

For example the following uri parses as a URI with a scheme of "file" and path of "/tmp/example.txt":
"file:///tmp/example.txt", but if the resulting uri object is rendered it results in "file:/tmp/example.txt", which quri:uri and quri:parse-uri both fail to parse. quri should be able to parse uris that it renders.

Another less egregious inconsistency is with network relative URLs. If you parse "//example.com" it will treat it as a path. However, if you do something like (quri.uri:make-uri :host "example.com") it renders as "//example.com". I think that if the URL starts with two slashes, it should be treated as a network relative URI.

FYI the behaviour in puri, is that it will parse both "file:///tmp/example.txt" and "file:/tmp/example.txt" into an object that renders as "file:///tmp/example.txt", and will parse "//example.com" as a URI with a host of example.com.

**Comment by AlbertoEAF** [comment]
Is this closed @tmccombs ?

**Comment by AlbertoEAF** [comment]
Thank you @tmccombs ;)
